
defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  pre-build:
    working_directory: ~/gatsbyBlog
    <<: *defaults
    steps:
      - checkout:
          path: ~/gatsbyBlog/
      - attach_workspace:
          at: ~/gatsbyBlog/

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/gatsbyBlog
          paths:
            - node_modules
  lint:
    working_directory: ~/gatsbyBlog
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/gatsbyBlog
      - run: npm run lint

  gatsby-deploy:
    working_directory: ~/gatsbyBlog
    <<: *defaults
    steps:
      - checkout:
          path: ~/gatsbyBlog/
      - attach_workspace:
          at: ~/gatsbyBlog
      - run:
          command: |
            sudo apt-get -y -qq install awscli
            CI=false npm run build:ci
            aws s3 sync public/ s3://weshoot.it/  --region eu-west-1 --delete
workflows:
  version: 2
  front-backend:
    jobs:
      - pre-build:
          filters:
            branches:
              only:
                - staging
      - lint:
          requires:
            - pre-build
      - gatsby-deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - staging